version: 2

project_name: probedesk

env:
  - CGO_ENABLED=1

before:
  hooks:
    - rsrc -ico icon.ico -arch amd64 -o rsrc_windows_amd64.syso
    - rsrc -ico icon.ico -arch arm64 -o rsrc_windows_arm64.syso

builds:
  - id: probedesk
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    binary: probedesk
    flags:
      - -trimpath=false

archives:
  - id: windows
    builds: [probedesk]
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - install.ps1

release:
  draft: false
  prerelease: false
  github:
    owner: RainyRoot
    name: ProbeDesk
